name: Skin Analysis
model_name: densenet
ckpt_path: checkpoints/
history_path: metrics/
train_data_path: ../../dataset/train/
val_data_path: ../../dataset/val/
test_data_path: ../../dataset/testX/
image_size: 224